### ISSUE TITLE
System.ArgumentException - výjimka na pozadí?

### ISSUE THREAD

**Issue by crdo** [havit/Bonusario#10]
MM zadával odměny, do Errors přišla výjimka níže.
Data jsou uložena a uživatel o žádném problému neví.

Exception information
    Exception type: System.ArgumentException
    Exception message: Id

Request information
    Request URL: /Havit.Bonusario.Contracts.EntryFacade/UpdateEntry
    Request verb: POST
    User host address: 195.122.198.36
    Username: Melena, Michael
    IsAuthenticated: True
    AuthenticationType: AuthenticationTypes.Federation
    Referrer: 
    User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44

Exception details
System.ArgumentException: Id
   at Havit.Diagnostics.Contracts.Contract.ThrowException[TException](String message) in D:\BuildAgent2\_work\512\s\Havit.Core\Diagnostics\Contracts\Contract.cs:line 98
   at Havit.Diagnostics.Contracts.Contract.Requires[TException](Boolean condition, String userMessage) in D:\BuildAgent2\_work\512\s\Havit.Core\Diagnostics\Contracts\Contract.cs:line 45
   at Havit.Bonusario.Facades.EntryFacade.UpdateEntryAsync(EntryDto entryDto, CancellationToken cancellationToken) in D:\BuildAgent2\_work\561\s\Facades\EntryFacade.cs:line 132
   at ProtoBuf.Grpc.Internal.Reshape.<EmptyTask>g__Awaited|2_0(Task t) in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 51
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext) in /_/src/Shared/Server/UnaryServerMethodInvoker.cs:line 81
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext) in /_/src/Shared/Server/UnaryServerMethodInvoker.cs:line 81
   at ProtoBuf.Grpc.Configuration.ServerExceptionsInterceptorBase.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation) in /_/src/protobuf-net.Grpc/Configuration/SimpleRpcExceptionsInterceptor.cs:line 75

Exception details (with Ben.Demystifier)
System.ArgumentException: Id
   at void Havit.Diagnostics.Contracts.Contract.ThrowException<TException>(string message) in D:/BuildAgent2/_work/512/s/Havit.Core/Diagnostics/Contracts/Contract.cs:line 98
   at void Havit.Diagnostics.Contracts.Contract.Requires<TException>(bool condition, string userMessage) in D:/BuildAgent2/_work/512/s/Havit.Core/Diagnostics/Contracts/Contract.cs:line 45
   at async Task Havit.Bonusario.Facades.EntryFacade.UpdateEntryAsync(EntryDto entryDto, CancellationToken cancellationToken) in D:/BuildAgent2/_work/561/s/Facades/EntryFacade.cs:line 132
   at async Task<Empty> ProtoBuf.Grpc.Internal.Reshape.EmptyTask(Task task)+Awaited(?) in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 51
   at async Task<TResponse> Grpc.Shared.Server.UnaryServerMethodInvoker<TService, TRequest, TResponse>.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext) x 2 in /_/src/Shared/Server/UnaryServerMethodInvoker.cs:line 81
   at async Task<TResponse> ProtoBuf.Grpc.Configuration.ServerExceptionsInterceptorBase.UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation) in /_/src/protobuf-net.Grpc/Configuration/SimpleRpcExceptionsInterceptor.cs:line 75

Application information
    Assembly: Havit.Bonusario.Web.Server
    Assembly Version: 1.0.0.0
    Product Version: 1.0.0

Event information
    Event time: 11/16/2021 1:31:05 PM +00:00
    Event UTC time: 11/16/2021 1:31:05 PM +00:00

**Comment by hakenr** [comment]
(@jirikanda BTW EditContext.OnFieldChanged se volá nějak i na disabled formulářích. Viz commit.)

**Comment by jirikanda** [comment]
@hakenr Pokud vidím dobře, volá se ze dvou míst: InputBase.CurrentValue (setter) a InputBase.CurrentValueAsString (setter).
Na jakém prvku UI k tomu dochází? Nicméně ochranu nastavení hodnoty neřešíme s ohledem na "disabled", protože "disabled" použijeme pouze pro nastavení stavu v UI.

Prověřím to, v podstatě je to v podstatě security issue.

**Comment by hakenr** [comment]
@jirikanda Spíš se musím podívat, proč se z klienta vůbec volá API, když je tam tato podmínka:
```csharp
private void EditContext_OnFieldChanged(object sender, FieldChangedEventArgs e)
		{
			if ((Entry.Id == default) && (Entry.Submitted is not null))
			{
				return;
			}
```
